language: java
sudo: true
addons:
  postgresql: "9.6"

install: true

dist: trusty

#deploy:
#  provider: heroku
#  app: mynotes
#  on:
#    branch:
#      - master
#  api_key:
#    secure: $HEROKU_API_KEY

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

before_script:
  - psql -c "create database mynotes;" -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'sa'"

services:
  - postgresql

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean build


notifications:
  email:
    recipients:
      - bass-2000@yandex.ru
    on_success: always # default: change